version: '3.8'
services:
  mysql:
    container_name: amour_en_defis_db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: amour
    ports:
      - "3306:3306"

  php:
    container_name: amour_en_defis
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${UID:-1000}
    ports:
      - "81:80"
    volumes:
      - './AmourEnDefis:/var/www/html'
    restart: on-failure

networks:
  amour-en-defis:
    name: amour-en-defis
    driver: bridge